SERVER:
  PORT: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://localhost:3396/chickenfeed
    username: root
    password: password
  flyway:
    enabled: true

ticket:
  stream:
    size:
      init: 10
      maximum: 10

logging:
  level:
    me:
      donald:
        chickenfeed: debug