SERVER:
  PORT: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://localhost:3396/lottos
    username: root
    password: password
  flyway:
    enabled: true
